### ISSUE TITLE
[Bug] Error when I rollup 

### ISSUE THREAD

**Issue by Jwuthri** [creativetimofficial/ct-argon-dashboard-pro-svelte#4]
### Version
1.0.0
### Reproduction link
https://jsfiddle.net/
### Operating System
Linux ubuntu
### Device
laptop
### Browser & Version
chrome
### Steps to reproduce
npm install
npm run dev

### What is expected?
it sould work, it's just the second step in the doc .....
### What is actually happening?
░▒▓    ~/Doc/G/W/s/argon-dashboard-pro-svelte-v1.0.0 ▓▒░ npm run dev

> argon-dashboard-pro-svelte@1.0.0 dev /home/jwuthri/Documents/Github/Web/svelte/argon-dashboard-pro-svelte-v1.0.0
> rollup -c -w

[!] Error: Package subpath './compiler.js' is not defined by "exports" in /home/jwuthri/Documents/Github/Web/svelte/argon-dashboard-pro-svelte-v1.0.0/node_modules/svelte/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in /home/jwuthri/Documents/Github/Web/svelte/argon-dashboard-pro-svelte-v1.0.0/node_modules/svelte/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jwuthri/Documents/Github/Web/svelte/argon-dashboard-pro-svelte-v1.0.0/node_modules/rollup-plugin-svelte/index.js:11:4)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon-dashboard-pro-svelte@1.0.0 dev: `rollup -c -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon-dashboard-pro-svelte@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jwuthri/.npm/_logs/2021-01-26T05_51_28_657Z-debug.log

---

**Comment by einazare** [comment]
Hello there, @Jwuthri 

Sorry for this late reply. The product was made by a third party that decided to not offer support, so Creative Tim just took the support for it.
To solve the issues you are having, please download and install [NodeJS LTS version](https://nodejs.org/en/), none of our products work with NodeJS (current) version due to our dependencies. We'll add this warning inside our live docs here in a few days when we'll release a new version of this product with updated dependencies as well.

Also, you will need to do the following:
```
npm i -E -D rollup-plugin-postcss postcss
```
After that, you need to go inside rollup.config.js and add inside the plugins array the following:
```
        postcss({
          extensions: [ '.css' ],
        }),
```
This will solve the rollup issues.
If you will have an error from google maps, you will also need to go inside `src/views/Dashboard/Maps/googleMaps.svelte` and replace 
```
import GoogleMapsLoader from "google-maps";
``` 
with 
```
import {Loader as GoogleMapsLoader} from "google-maps";
```

In a few days we'll release a new version of this product with the above fixes.

Best,
Manu

**Comment by dragosct** [comment]
This is already integrated on the new update released.
